### PR TITLE
node_capacity argument of Quadtree instead of global and fixed.

### PR DESCRIPTION
**Pull request by Profpatsch**
Can set it from outside of the module now.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Attention: Changes API …

**Comment by Profpatsch** [comment]
But: The variable is pretty much useless without this, because I can’t set it at all otherwise.

**Comment by foolusion** [comment]
Can you change the variable name to nodeCapacity to conform with naming standards. Otherwise looks good.

quadtree.go:71:2: don't use underscores in Go names; struct field node_capacity should be nodeCapacity
quadtree.go:81:25: don't use underscores in Go names; func parameter node_capacity should be nodeCapacity

**Comment by Profpatsch** [comment]
Done.

**Comment by foolusion** [comment]
Thank you! Closed

**Pull request merged**
